### PR TITLE
Module_5 with an express error

### PR DESCRIPTION
**Pull request by ghost**
I think this is mostly finished but I got stuck as I was trying to work through the errors.  I can tell that this most recent error has something to do with express, but I'm not sure where the breakdown is.  I checked to make sure that it was installed and required.  I'm not sure where else to look for issues.  Could you please take a look? Thanks, Karen

### CODE REVIEW

**Comment by jamdon** [comment]
In truckRoutes.js, return the router object from the function that wraps the router.route calls and it should clear up the error you're seeing.

**Comment by jamdon** [comment]
Let me know if you want it graded as is or if you wanted to update it.

**Comment by ghost** [comment]
I'm going to update it.  Probably this weekend.  Thanks.

**Comment by ghost** [comment]
I revised my code and revised it again.  I even commented mine out and replaced it with code that I knew was working and it wouldn't work. I think I may not have MongoDB installed correctly. Or maybe installed twice. Or a typo that I can't seem to catch. I'm not sure what's wrong. It should work, but doesn't.

**Comment by jamdon** [comment]
Your code ran fine for me, so I'm guessing the problem is something with your environment. If you want me to troubleshoot, send me the errors you're seeing. :+1:

**Pull request closed without merging**
